import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  // TODO: enable on more examples
  //   sidebar: [
  //     {
  //       type: "category",
  //       label: "Introductory",
  //       description: "Easy to follow examples to get you started.",
  //       items: [{ type: "autogenerated", dirName: "examples/introductory" }],
  //     },
  //     {
  //       type: "category",
  //       label: "Intermediate",
  //       description: "Medium complexity examples for users with some experience.",
  //       items: [{ type: "autogenerated", dirName: "examples/intermediate" }],
  //     },
  //     {
  //       type: "category",
  //       label: "Advanced",
  //       description: "Complex examples for power users.",
  //       items: [{ type: "autogenerated", dirName: "examples/advanced" }],
  //     },
  //   ],

  sidebar: [
    {
      type: "doc",
      id: "examples/advanced/raycast",
    },
    {
      type: "doc",
      id: "examples/intermediate/mcp",
    },
    {
      type: "doc",
      id: "examples/introductory/journal",
    },
  ],
};

export default sidebar.sidebar;
