import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  // TODO: enable on more examples
  //   sidebar: [
  //     {
  //       type: "category",
  //       label: "Introductory",
  //       description: "Easy to follow examples to get you started.",
  //       items: [{ type: "autogenerated", dirName: "examples/introductory" }],
  //     },
  //     {
  //       type: "category",
  //       label: "Intermediate",
  //       description: "Medium complexity examples for users with some experience.",
  //       items: [{ type: "autogenerated", dirName: "examples/intermediate" }],
  //     },
  //     {
  //       type: "category",
  //       label: "Advanced",
  //       description: "Complex examples for power users.",
  //       items: [{ type: "autogenerated", dirName: "examples/advanced" }],
  //     },
  //   ],

  sidebar: [
    {
      type: "doc",
      id: "examples/overview",
    },
    {
      type: "category",
      label: "Featured",
      description: "Official projects by the Anytype team demonstrating best practices and capabilities.",
      items: [{ type: "autogenerated", dirName: "examples/featured" }],
      collapsed: false,
    },
    {
      type: "category",
      label: "Community",
      description: "Projects by the community showcasing creative implementations and use cases.",
      items: [{ type: "autogenerated", dirName: "examples/community" }],
      collapsed: false,
    },
  ],
};

export default sidebar.sidebar;
