import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  guidesSidebar: [
    {
      type: "category",
      label: "Get Started",
      collapsed: false,
      description: "The basic concepts you need to get started.",
      items: [{ type: "autogenerated", dirName: "guides/get-started" }],
    },
    {
      type: "category",
      label: "Fundamentals",
      collapsed: false,
      description: "Core technical details about how the Anytype API works.",
      items: [{ type: "autogenerated", dirName: "guides/fundamentals" }],
    },
  ],
};

export default sidebar.guidesSidebar;
